---
title: "Optimizing codes"
output: html_notebook
---

## Load required packages

```{r}
library(tidyverse)
library(tidyr)
library(profvis)
library(microbenchmark)
```


## Profilling the outbreak_model function

```{r}
## current version of all function
source(file.path("..", "code", "functions_stop01.R"))

## simulate population
pop <- pop_sim(n = 500, hh_max = 8, hh_mean = 4, ws_max = 100, ws_mean = 50, seed = 1)

## simulate contact
contactnet <- contact_sim(pop = pop,
                          assume = cbind(hh = c(0.1, 0.2, 0.4, 0.3),
                                         ws = c(0.69, 0.2, 0.1, 0.01),
                                         ot = c(0.889, 0.1, 0.01, 0.001)),
                          seed = 1)

## initialize parameters
ncore <- 4
n_sim <- 1
net <- contactnet
n_initial <- 1
p_asym <- 0.4
d_recovery <- 14
p_presym <- 0.4
p_asymtrans <- 0.5
R <- c(2, 4, 6.5, 8)
p_outside <- 0.001
p_contact <- 0.9
cap_max_days <- 30
outdir <- "simulation"
control_t <- c(1, 5, 10)
full_lockdown_assume <- list(cbind(hh = c(0.01, 0.02, 0.5, 0.47),
                              ws = c(0.9889, 0.01, 0.001, 0.0001),
                              ot = c(0.99889, 0.001, 0.0001, 0.00001)),
                             cbind(hh = c(0.01, 0.02, 0.5, 0.47),
                                   ws = c(1, 0, 0, 0),
                                   ot = c(1, 0, 0, 0)))
```

```{r}
l00 <- profvis(
  outbreak_model(
                      pop = pop,
                      net = net,
                      n_initial = n_initial,
                      p_asym = p_asym,
                      d_recovery = d_recovery,
                      p_presym = p_presym,
                      p_asymtrans = p_asymtrans,
                      R = R[3],
                      p_outside = p_outside,
                      p_contact = p_contact,
                      cap_max_days = cap_max_days,
                      outdir = file.path(outdir, "test", paste("scenario", 1, sep = "_")),
                      control = "none"
                    )
)

l01 <- profvis(
  outbreak_model(
                      pop = pop,
                      net = net,
                      n_initial = n_initial,
                      p_asym = p_asym,
                      d_recovery = d_recovery,
                      p_presym = p_presym,
                      p_asymtrans = p_asymtrans,
                      R = R[3],
                      p_outside = p_outside,
                      p_contact = p_contact,
                      cap_max_days = cap_max_days,
                      outdir = file.path(outdir, "test", paste("scenario", 1, sep = "_")),
                      control = "full_lockdown",
                      control_t = control_t[2],
                      control_assume = full_lockdown_assume[[1]]
                    )
)
```
```{r}
l00 ## contact_step ~ 750 ms, 42 Mb, outbreak_step0 ~ 330 ms, 11 MB
l01 ## contact_sim ~ 2820 ms, contact_step ~ 3070 ms, outbreak_step0 ~ 1010 ms
```


